### ISSUE TITLE
Generic signTx

### ISSUE THREAD

**Issue by reichert-splinterlands** [ecency/hivesigner-ui#82]
It would be great if hivesigner.com/signs would also support a generic `signTx` function, similar to keychains `requestSignTx` (https://github.com/hive-keychain/hive-keychain-extension/blob/master/documentation/README.md#requestsigntx)

Example:
https://hivesigner.com/sign/tx?authority=posting&account=wolf&tx=STRINGIFIED_TX&redirect_uri=http://localhost:8000?tx={{tx}}

**Comment by feruzm** [comment]
You can already sign/request multiple operations/transactions with [Hivesigner SDK](https://github.com/ecency/hivesigner-sdk)
Example:
```
const op: Operation = [
    "transfer_from_savings",
    {
      from,
      to,
      amount,
      memo,
      request_id: rid
    }
  ];
  const cop: Operation = [
    "cancel_transfer_from_savings",
    {
      from,
      request_id: rid
    }
  ];

  const params: Parameters = { callback: `https://ecency.com/@${from}/wallet` };
  return hs.sendOperations([op, cop], params, () => {});
  ```
This does create special url to sign and broadcast operation/transaction.

**Comment by tre-dev** [comment]
But this works via a token received, right? I need a UX flow where the user broadcasts it himself

**Comment by feruzm** [comment]
@tre-dev actually no it doesn't require token, underlying library keychain uses also used by hivesigner which is `hive-uri` and hivesigner sdk helps you to generate unique link for any option, above script is just example you can see it will generate hivesigner link for you to sign, since `Active` operations are hot sign meaning it should be signed by user, you should be able to generate any transaction signing with above snippet.
